/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.crudDescuento;

import controller.descuento.CrudDescuento;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.LoginUser;
import model.descuento.Descuento;

/**
 *
 * @author fernandacancinoreyes
 */
public class updateDescuentos extends javax.swing.JFrame {

    LoginUser mod;
    /**
     * Creates new form updateDescuentos
     */
    public updateDescuentos() {
        
        initComponents();
        
        /*Para dejar la pantalla centrada*/
        this.setLocationRelativeTo(null);
        
        txtIdDescuentoMod.setVisible(false);
        
    }
    public updateDescuentos(LoginUser mod) {
        this.mod=mod;
        
        initComponents();
        
        /*Para dejar la pantalla centrada*/
        this.setLocationRelativeTo(null);
        
        txtIdDescuentoMod.setVisible(false);
        
    }
    
    private void limpiarDatos(){
        
        txtMinPuntosDescuentoMod.setText("");
        txtMaxPuntosDescuentoMod.setText("");
        txtTopeDescuentoMod.setText("");
        txtPorcentajeDescuentoMod.setText("");
        
    }
    
    private void verificaDatos(){
        if(    txtMinPuntosDescuentoMod.getText().trim().length() != 0 
            && txtMaxPuntosDescuentoMod.getText().trim().length() != 0
            && txtTopeDescuentoMod.getText().trim().length() != 0
            && txtPorcentajeDescuentoMod.getText().trim().length() != 0
           ) {
            //si los datos son correctamente insertados se ejecuta funcion para que guarde
            //agregaDesucento()
            try {
                modificar();
                //agregaDesucento();
            } catch (SQLException ex) {
                Logger.getLogger(createDescuentos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            }
        else {
            JOptionPane.showMessageDialog(null, "Debe insertar todos los datos");
        }
    }
    
    //metodo para modificar 
   public void modificar() throws SQLException {//throws SQLException{
       
        Descuento dscto = new Descuento();
        CrudDescuento controllerDscto = new CrudDescuento();
        
        dscto.setIdDescuento(parseInt(txtIdDescuentoMod.getText()));
        
        dscto.setMinPuntos(parseInt(txtMinPuntosDescuentoMod.getText()));
        dscto.setMaxPuntos(parseInt(txtMaxPuntosDescuentoMod.getText()));
        dscto.setPorcentajeDescuento(parseInt(txtPorcentajeDescuentoMod.getText()));
        dscto.setTopeDescuento(parseInt(txtTopeDescuentoMod.getText())); 
        
        controllerDscto.modificarDescuento(dscto);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMinPuntosDescuentoMod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaxPuntosDescuentoMod = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPorcentajeDescuentoMod = new javax.swing.JTextField();
        txtTopeDescuentoMod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnGuardarDescuentoMod = new javax.swing.JButton();
        btnVolverDescuentoMod = new javax.swing.JButton();
        txtIdDescuentoMod = new javax.swing.JTextField();
        txtIdProductoMod = new javax.swing.JTextField();
        dtFechaVencimientoMod = new com.toedter.calendar.JDateChooser();
        btnImagenMod = new javax.swing.JButton();
        lblImagenMod = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(208, 211, 212));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descuento.png"))); // NOI18N
        jLabel1.setText("  Modificar Descuento");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Tiendas Retail Mis Ofertas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Minimo Puntos");

        txtMinPuntosDescuentoMod.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtMinPuntosDescuentoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinPuntosDescuentoModActionPerformed(evt);
            }
        });
        txtMinPuntosDescuentoMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinPuntosDescuentoModKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Maximo Puntos");

        txtMaxPuntosDescuentoMod.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtMaxPuntosDescuentoMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaxPuntosDescuentoModKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Porcentaje Descuento");

        txtPorcentajeDescuentoMod.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPorcentajeDescuentoMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcentajeDescuentoModKeyTyped(evt);
            }
        });

        txtTopeDescuentoMod.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTopeDescuentoMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTopeDescuentoModKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Tope Descuento ($)");

        btnGuardarDescuentoMod.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGuardarDescuentoMod.setText("Guardar");
        btnGuardarDescuentoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDescuentoModActionPerformed(evt);
            }
        });

        btnVolverDescuentoMod.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnVolverDescuentoMod.setText("Volver");
        btnVolverDescuentoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverDescuentoModActionPerformed(evt);
            }
        });

        txtIdDescuentoMod.setText("id");
        txtIdDescuentoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDescuentoModActionPerformed(evt);
            }
        });

        txtIdProductoMod.setEditable(false);

        btnImagenMod.setText("Imagen...");
        btnImagenMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnGuardarDescuentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnVolverDescuentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdDescuentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaxPuntosDescuentoMod)
                            .addComponent(txtMinPuntosDescuentoMod)
                            .addComponent(txtTopeDescuentoMod, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPorcentajeDescuentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(txtIdDescuentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMinPuntosDescuentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaxPuntosDescuentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPorcentajeDescuentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTopeDescuentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolverDescuentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarDescuentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMinPuntosDescuentoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinPuntosDescuentoModActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMinPuntosDescuentoModActionPerformed

    private void txtMinPuntosDescuentoModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinPuntosDescuentoModKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo Numeros");
        }

        //O tambien se puede validar de la siguiente forma
        /*
        //VALIDA EL INGRESO DE DIGITOS
        if (Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo letras");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Bien ha ingresado un número");
        }
        */

    }//GEN-LAST:event_txtMinPuntosDescuentoModKeyTyped

    private void txtMaxPuntosDescuentoModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaxPuntosDescuentoModKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo Numeros");
        }

    }//GEN-LAST:event_txtMaxPuntosDescuentoModKeyTyped

    private void txtPorcentajeDescuentoModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeDescuentoModKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo Numeros");
        }
    }//GEN-LAST:event_txtPorcentajeDescuentoModKeyTyped

    private void txtTopeDescuentoModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTopeDescuentoModKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo Numeros");
        }
    }//GEN-LAST:event_txtTopeDescuentoModKeyTyped

    private void btnGuardarDescuentoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDescuentoModActionPerformed

        verificaDatos();
        limpiarDatos();
         readDescuento rd = new readDescuento(mod);
            rd.setVisible(true); 
            rd.pack();
        this.setVisible(false);

    }//GEN-LAST:event_btnGuardarDescuentoModActionPerformed

    private void btnVolverDescuentoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverDescuentoModActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        readDescuento rp = new readDescuento(mod);
        rp.setVisible(true);
        rp.pack();

    }//GEN-LAST:event_btnVolverDescuentoModActionPerformed

    private void txtIdDescuentoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDescuentoModActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIdDescuentoModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateDescuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateDescuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateDescuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateDescuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateDescuentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarDescuentoMod;
    private javax.swing.JButton btnImagenMod;
    private javax.swing.JButton btnVolverDescuentoMod;
    public static com.toedter.calendar.JDateChooser dtFechaVencimientoMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblImagenMod;
    public static javax.swing.JTextField txtIdDescuentoMod;
    public static javax.swing.JTextField txtIdProductoMod;
    public static javax.swing.JTextField txtMaxPuntosDescuentoMod;
    public static javax.swing.JTextField txtMinPuntosDescuentoMod;
    public static javax.swing.JTextField txtPorcentajeDescuentoMod;
    public static javax.swing.JTextField txtTopeDescuentoMod;
    // End of variables declaration//GEN-END:variables
}
