/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;



import conectorBD.JavaConnectDb;
import view.crudDescuento.readDescuento;
import view.Tienda.readTienda;
import view.crudEmpresas.readEmpresa;
import view.crudProductos.readProductos;
import view.crudProductos.readProductos;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;

import view.crudUsuarios.readUsuario;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.GenerarArchivoBItxt;
import model.Oferta.Oferta2BI;
import view.crudOferta.readOferta;

/**
 *
 * @author fernandacancinoreyes
 */
public class menuPrincipal extends javax.swing.JFrame {
    

    /**
     * Creates new form menuPrincipal
     */
   public menuPrincipal() throws ClassNotFoundException, IllegalAccessException, InstantiationException, UnsupportedLookAndFeelException {
        initComponents();
        
        /*PARA QUE LA PANTALLA APAREZCA CENTRADA*/
        this.setLocationRelativeTo(null);
          
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    }
   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMantenedorProducto = new javax.swing.JButton();
        btnMantenedorOferta = new javax.swing.JButton();
        btnMantenedorEmpresa = new javax.swing.JButton();
        btnMantenedorTienda = new javax.swing.JButton();
        btnMantenedorDescuento = new javax.swing.JButton();
        btnMantenedorUsuario = new javax.swing.JButton();
        btnConsultaValoracionPorTienda = new javax.swing.JButton();
        btnDescargaArchivosBI = new javax.swing.JButton();
        btnReporteResumenPorTienda = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(208, 211, 212));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Tiendas Retail Mis Ofertas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        btnMantenedorProducto.setText("Mantenedor Producto");
        btnMantenedorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenedorProductoActionPerformed(evt);
            }
        });

        btnMantenedorOferta.setText("Mantenedor Oferta");
        btnMantenedorOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenedorOfertaActionPerformed(evt);
            }
        });

        btnMantenedorEmpresa.setText("Mantenedor Empresa");
        btnMantenedorEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenedorEmpresaActionPerformed(evt);
            }
        });

        btnMantenedorTienda.setText("Mantenedor Tienda");
        btnMantenedorTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenedorTiendaActionPerformed(evt);
            }
        });

        btnMantenedorDescuento.setText("Mantenedor Descuento");
        btnMantenedorDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenedorDescuentoActionPerformed(evt);
            }
        });

        btnMantenedorUsuario.setText("Mantenedor Usuario");
        btnMantenedorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenedorUsuarioActionPerformed(evt);
            }
        });

        btnConsultaValoracionPorTienda.setText("Consulta Valoracion por Tienda");

        btnDescargaArchivosBI.setText("Descarga Archivos BI");
        btnDescargaArchivosBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargaArchivosBIActionPerformed(evt);
            }
        });

        btnReporteResumenPorTienda.setText("Reporte Resumen por Tienda");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMantenedorProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMantenedorOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMantenedorEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMantenedorTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMantenedorDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(btnMantenedorUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultaValoracionPorTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDescargaArchivosBI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReporteResumenPorTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMantenedorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultaValoracionPorTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMantenedorOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteResumenPorTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMantenedorEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDescargaArchivosBI, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMantenedorTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMantenedorDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMantenedorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
 
    
    
    private void btnMantenedorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenedorProductoActionPerformed
       /*PRODUCTOS*/
       this.setVisible(false);
       readProductos rp = new readProductos();
      rp.setVisible(true);
        rp.pack();
    }//GEN-LAST:event_btnMantenedorProductoActionPerformed

    private void btnMantenedorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenedorUsuarioActionPerformed
        // TODO add your handling code here: 
        this.setVisible(false);
        readUsuario ru = new readUsuario();
        ru.setVisible(true);
    }//GEN-LAST:event_btnMantenedorUsuarioActionPerformed

    private void btnMantenedorOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenedorOfertaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        readOferta ro= new  readOferta();
        ro.setVisible(true);
    }//GEN-LAST:event_btnMantenedorOfertaActionPerformed

    private void btnMantenedorDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenedorDescuentoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        readDescuento rd = new readDescuento();
        rd.setVisible(true);
    }//GEN-LAST:event_btnMantenedorDescuentoActionPerformed

    private void btnMantenedorEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenedorEmpresaActionPerformed
      readEmpresa re = new readEmpresa();
        this.setVisible(false);
        re.setVisible(true);
        re.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_btnMantenedorEmpresaActionPerformed

    private void btnMantenedorTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenedorTiendaActionPerformed
        // TODO add your handling code here:
         readTienda re = new readTienda();
        this.setVisible(false);
        re.setVisible(true);
        re.pack();  
    }//GEN-LAST:event_btnMantenedorTiendaActionPerformed

    private void btnDescargaArchivosBIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargaArchivosBIActionPerformed
        // TODO add your handling code here:
     
                    String Ruta="C:\\ReportesBI";
                      File ReporteBI=new File(Ruta);
                      
                      if(ReporteBI.exists())
                      {
                          String Ruta2=null;
         int s = JOptionPane.showConfirmDialog(null, "El Archivo se a descargado exitosamente se encuentra en :\n "+Ruta+"\n"+"¿Desea mostrar el contenido?","Si/no",JOptionPane.YES_NO_OPTION);
                    if(s == 0){
                        
                        JFileChooser fileChooser = new JFileChooser("C:\\ReportesBI\\");
                int seleccion = fileChooser.showOpenDialog(null);
                
                if (seleccion == JFileChooser.APPROVE_OPTION)
                   {
               File fichero = fileChooser.getSelectedFile();
                      Ruta2= fichero.getAbsolutePath();
                       
                    GenerarArchivoBItxt.abrirarchivo(Ruta2);
                    }    
                        
                     
                    }
        
                         
                      }
                      else
                      {
                         JOptionPane.showMessageDialog(null, "La Carpeta de ReportesBI no existe o esta vacía.\n"
                                 + " Porfavor espere hasta el día Lunes para que se cree  genere el primer reporte gracias por su comprensión \n"
                                 + " en especial tu feña curiosa...  ");
                         
                         
                      }
         
        
        
             
        
        
        
        
        
      
			
			
			
			
        
        
    }//GEN-LAST:event_btnDescargaArchivosBIActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new menuPrincipal().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(menuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(menuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(menuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(menuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaValoracionPorTienda;
    private javax.swing.JButton btnDescargaArchivosBI;
    private javax.swing.JButton btnMantenedorDescuento;
    private javax.swing.JButton btnMantenedorEmpresa;
    private javax.swing.JButton btnMantenedorOferta;
    private javax.swing.JButton btnMantenedorProducto;
    private javax.swing.JButton btnMantenedorTienda;
    private javax.swing.JButton btnMantenedorUsuario;
    private javax.swing.JButton btnReporteResumenPorTienda;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
